# Generated by Django 5.0.6 on 2024-06-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingdate',
            new_name='booking_date',
        ),
    ]
